### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by cwjohn13** [INFO-526-SU24/final-project-ultraviolets369#2]
The following is the peer review of the project proposal by Cole Johnson (cwjohn13)

- Describe the goal of the project.
Their are 2 goals of this project, the first is to determine if peoples states coffee preferences (based on roast level, etc.) align with their favorite coffee from the taste test.
The second is to determine how bitterness, acidity and personal preference vary for each sample and determining if age is a factor in these results.

- Describe the data used or collected.
The Data set is a result of 4 coffee samples being sent to over 4000 Americans along with a survey about which coffee they liked best out of the samples as well as their regular preference in coffee. The data set also includes other variables such as gender and age to separate different coffee drinkers into categories.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The first question will be answered using a heat map with the variables roast_level (which is the response to "what roast level do you prefer") and prefer_overall (which is a response to "what was your favorite overall coffee").
The second question will be answered using a grouped bar chart for ratings of bitterness, acidity and personal preference for each of the 4 sampled coffees. This response will be faceted by rating and grouped by age to determine if age is a factor in coffee preference. 

- Is there anything that is unclear from the proposal?
The analysis plan for question 1 has me a bit confused, I get overall what the plan is however I think you should explain what exactly you will be looking for in the heat map when it has been plotted.

- Provide constructive feedback on how the team might be able to improve their project.
It looks like you are doing this project as an individual and not a team. From what I understand if you are doing it as an individual you only need to be answering 1 question but you will need to create 2 plots for that 1 question. 
Possibly make your question more broad so both of your analysis plans fall into a single question?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I am most interested in your second analysis plan, I think the analysis by age will be really interesting and should have some good insights to go along with it.

- Provide constructive feedback on any issues with file and/or code organization.
Only issue I see is that in the dataset for race/ethnicity and gender, they both have results for "Other (please specify)" I would try to mutate that response into just "Other". It should make the data look a bit better in my opinion, since we do not have the written specification that they likely provided.

- (Optional) Any further comments or feedback?
N/A

**Comment by ultraviolets369** [comment]
Hey Cole, 

Thank you for your feedback! I removed my question that compared stated coffee preference to the preferred coffee in the experiment. I decided to focus on ratings of preference, acidity, and bitterness grouped by age.
